### ISSUE TITLE
Blizzart Authentication

### ISSUE THREAD

**Issue by EricBatlle** [ZeShmoutt/Blizzard-API-For-Unity#1]
Hey ZeShmoutt, first of all, AWESOME repo, reeeeeeally awesome.

My "issue": 
I don't get how to use your library to achieve a login via Blizzard Authentication, it is even possible with your library? Do you have any advice? Thanks!

**Comment by ZeShmoutt** [comment]
It's not possible currently, because the API user login process doesn't support client-only apps, and Unity doesn't natively support live web page display.

There's some stuff on github and the asset store for the web page display that may solve the problem, but I'd rather keep my library as standalone as possible, so for now it's pretty much "will not fix". Sorry.

**Comment by EricBatlle** [comment]
Okey, thanks for the explanation ZeShmoutt, I'll close the issue!
